version: '3.1'

services:
  quote:
    ports:
      - '8080:8080'
    expose:
      - '8080'
    image: goodfatcat/quotetrialtask
    networks:
      - mynetwork
    container_name: 'quote-trial-task'
    restart: always
networks:
  mynetwork: